[project]
name = "smithers"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain>=0.3.13",
    "langchain-core>=0.3.28",
    "langchain-ollama>=0.2.2",
    "langgraph>=0.2.60",
]
